In [1]:
import pandas as pd

In [2]:
def get_data(year="2015-16"):
    
    ret = pd.read_csv("data/CTSchoolDaySAT" + year + ".csv",skiprows=3,header=[0,1])
    
    ret.columns = ['District',
                   'District Code',
                   'Subject',
                   'Total Number of Students',
                   'Total Number Tested',
                   'Connecticut School Day SAT Participation Rate',
                   'Total Numberwith Scored Tests',
                   'Level 1 Not Met Count',
                   'Level 1 Not Met Count %',
                   'Level 2 Approaching Count',
                   'Level 2 Approaching %',
                   'Level 3 Met Count',
                   'Level 3 Met Count %',
                   'Level 4 Exceeded Count',
                   'Level 4 Exceeded Count %',
                   'Level 3&4 Met or Exceeded Count',
                   'Level 3&4 Met or Exceeded %',
                   'Average Score']
    
    ret["year"] = year
    
    
    ret = ret.set_index(["District","year","Subject"])
    
    return ret

In [3]:
scores_17 = get_data(year="2016-17")
scores_16 = get_data(year="2015-16")
scores_17.head(10)

                                                                 District Code  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA        ="2880013"
                                                         Math       ="2880013"
Amistad Academy District                         2016-17 ELA        ="2790013"
                                                         Math       ="2790013"
Ansonia School District                          2016-17 ELA        ="0020011"
                                                         Math       ="0020011"
Area Cooperative Educational Services            2016-17 ELA        ="2440014"
                                                         Math       ="2440014"
Avon School District                             2016-17 ELA        ="0040011"
                                                         Math       ="0040011"

                                                                 Total Number of Students  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                           39
                                                         Math                          39
Amistad Academy District                         2016-17 ELA                           50
                                                         Math                          50
Ansonia School District                          2016-17 ELA                          134
                                                         Math                         134
Area Cooperative Educational Services            2016-17 ELA                           18
                                                         Math                          18
Avon School District                             2016-17 ELA                          285
                                                         Math                         285

                                                                 Total Number Tested  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                      39
                                                         Math                     39
Amistad Academy District                         2016-17 ELA                      48
                                                         Math                     48
Ansonia School District                          2016-17 ELA                     127
                                                         Math                    127
Area Cooperative Educational Services            2016-17 ELA                      15
                                                         Math                     15
Avon School District                             2016-17 ELA                     282
                                                         Math                    282

                                                                 Connecticut School Day SAT Participation Rate  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                                             100.0
                                                         Math                                            100.0
Amistad Academy District                         2016-17 ELA                                              96.0
                                                         Math                                             96.0
Ansonia School District                          2016-17 ELA                                              94.8
                                                         Math                                             94.8
Area Cooperative Educational Services            2016-17 ELA                                                 *
                                                         Math                                                *
Avon School District                             2016-17 ELA                                              98.9
                                                         Math                                             98.9

                                                                 Total Numberwith Scored Tests  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                                39
                                                         Math                               38
Amistad Academy District                         2016-17 ELA                                47
                                                         Math                               47
Ansonia School District                          2016-17 ELA                               127
                                                         Math                              126
Area Cooperative Educational Services            2016-17 ELA                                15
                                                         Math                               13
Avon School District                             2016-17 ELA                               282
                                                         Math                              282

                                                                 Level 1 Not Met Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                         *
                                                         Math                        *
Amistad Academy District                         2016-17 ELA                         *
                                                         Math                       10
Ansonia School District                          2016-17 ELA                        38
                                                         Math                       57
Area Cooperative Educational Services            2016-17 ELA                         *
                                                         Math                        *
Avon School District                             2016-17 ELA                        14
                                                         Math                       13

                                                                 Level 1 Not Met Count %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                           *
                                                         Math                          *
Amistad Academy District                         2016-17 ELA                           *
                                                         Math                       21.3
Ansonia School District                          2016-17 ELA                        29.9
                                                         Math                       45.2
Area Cooperative Educational Services            2016-17 ELA                           *
                                                         Math                          *
Avon School District                             2016-17 ELA                         5.0
                                                         Math                        4.6

                                                                 Level 2 Approaching Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                            10
                                                         Math                           20
Amistad Academy District                         2016-17 ELA                             9
                                                         Math                           28
Ansonia School District                          2016-17 ELA                            26
                                                         Math                           48
Area Cooperative Educational Services            2016-17 ELA                             *
                                                         Math                            *
Avon School District                             2016-17 ELA                            19
                                                         Math                           46

                                                                 Level 2 Approaching %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                      25.6
                                                         Math                     52.6
Amistad Academy District                         2016-17 ELA                      19.1
                                                         Math                     59.6
Ansonia School District                          2016-17 ELA                      20.5
                                                         Math                     38.1
Area Cooperative Educational Services            2016-17 ELA                         *
                                                         Math                        *
Avon School District                             2016-17 ELA                       6.7
                                                         Math                     16.3

                                                                 Level 3 Met Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                    22
                                                         Math                   13
Amistad Academy District                         2016-17 ELA                    33
                                                         Math                    9
Ansonia School District                          2016-17 ELA                    52
                                                         Math                    *
Area Cooperative Educational Services            2016-17 ELA                     *
                                                         Math                    *
Avon School District                             2016-17 ELA                   120
                                                         Math                  104

                                                                 Level 3 Met Count %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                    56.4
                                                         Math                   34.2
Amistad Academy District                         2016-17 ELA                    70.2
                                                         Math                   19.1
Ansonia School District                          2016-17 ELA                    40.9
                                                         Math                      *
Area Cooperative Educational Services            2016-17 ELA                       *
                                                         Math                      *
Avon School District                             2016-17 ELA                    42.6
                                                         Math                   36.9

                                                                 Level 4 Exceeded Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                          *
                                                         Math                         *
Amistad Academy District                         2016-17 ELA                          *
                                                         Math                         0
Ansonia School District                          2016-17 ELA                         11
                                                         Math                         *
Area Cooperative Educational Services            2016-17 ELA                          *
                                                         Math                         *
Avon School District                             2016-17 ELA                        129
                                                         Math                       119

                                                                 Level 4 Exceeded Count %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                            *
                                                         Math                           *
Amistad Academy District                         2016-17 ELA                            *
                                                         Math                         0.0
Ansonia School District                          2016-17 ELA                          8.7
                                                         Math                           *
Area Cooperative Educational Services            2016-17 ELA                            *
                                                         Math                           *
Avon School District                             2016-17 ELA                         45.7
                                                         Math                        42.2

                                                                 Level 3&4 Met or Exceeded Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                                   *
                                                         Math                                  *
Amistad Academy District                         2016-17 ELA                                   *
                                                         Math                                  9
Ansonia School District                          2016-17 ELA                                  63
                                                         Math                                 21
Area Cooperative Educational Services            2016-17 ELA                                   *
                                                         Math                                  *
Avon School District                             2016-17 ELA                                 249
                                                         Math                                223

                                                                 Level 3&4 Met or Exceeded %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA                               *
                                                         Math                              *
Amistad Academy District                         2016-17 ELA                               *
                                                         Math                           19.1
Ansonia School District                          2016-17 ELA                            49.6
                                                         Math                           16.7
Area Cooperative Educational Services            2016-17 ELA                               *
                                                         Math                              *
Avon School District                             2016-17 ELA                            88.3
                                                         Math                           79.1

                                                                 Average Score
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2016-17 ELA               488
                                                         Math              494
Amistad Academy District                         2016-17 ELA               511
                                                         Math              467
Ansonia School District                          2016-17 ELA               478
                                                         Math              444
Area Cooperative Educational Services            2016-17 ELA                 *
                                                         Math                *
Avon School District                             2016-17 ELA               603
                                                         Math              611

In [4]:
# test that both sheets have the same column names
scores_17.columns == scores_16.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [5]:
scores_16.head()

                                                                 District Code  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA        ="2880013"
                                                         Math       ="2880013"
Amistad Academy District                         2015-16 ELA        ="2790013"
                                                         Math       ="2790013"
Ansonia School District                          2015-16 ELA        ="0020011"

                                                                 Total Number of Students  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                           32
                                                         Math                          32
Amistad Academy District                         2015-16 ELA                           45
                                                         Math                          45
Ansonia School District                          2015-16 ELA                          151

                                                                 Total Number Tested  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                      30
                                                         Math                     30
Amistad Academy District                         2015-16 ELA                      44
                                                         Math                     44
Ansonia School District                          2015-16 ELA                     138

                                                                 Connecticut School Day SAT Participation Rate  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                                              93.8
                                                         Math                                             93.8
Amistad Academy District                         2015-16 ELA                                              97.8
                                                         Math                                             97.8
Ansonia School District                          2015-16 ELA                                              91.4

                                                                 Total Numberwith Scored Tests  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                                30
                                                         Math                               30
Amistad Academy District                         2015-16 ELA                                44
                                                         Math                               44
Ansonia School District                          2015-16 ELA                               138

                                                                 Level 1 Not Met Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                         *
                                                         Math                        *
Amistad Academy District                         2015-16 ELA                         6
                                                         Math                       11
Ansonia School District                          2015-16 ELA                        37

                                                                 Level 1 Not Met Count %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                           *
                                                         Math                          *
Amistad Academy District                         2015-16 ELA                        13.6
                                                         Math                       25.0
Ansonia School District                          2015-16 ELA                        26.8

                                                                 Level 2 Approaching Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                             7
                                                         Math                           13
Amistad Academy District                         2015-16 ELA                             *
                                                         Math                           23
Ansonia School District                          2015-16 ELA                             *

                                                                 Level 2 Approaching %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                      23.3
                                                         Math                     43.3
Amistad Academy District                         2015-16 ELA                         *
                                                         Math                     52.3
Ansonia School District                          2015-16 ELA                         *

                                                                 Level 3 Met Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                    17
                                                         Math                   14
Amistad Academy District                         2015-16 ELA                    28
                                                         Math                    *
Ansonia School District                          2015-16 ELA                    62

                                                                 Level 3 Met Count %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                    56.7
                                                         Math                   46.7
Amistad Academy District                         2015-16 ELA                    63.6
                                                         Math                      *
Ansonia School District                          2015-16 ELA                    44.9

                                                                 Level 4 Exceeded Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                          *
                                                         Math                         *
Amistad Academy District                         2015-16 ELA                          *
                                                         Math                         *
Ansonia School District                          2015-16 ELA                          *

                                                                 Level 4 Exceeded Count %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                            *
                                                         Math                           *
Amistad Academy District                         2015-16 ELA                            *
                                                         Math                           *
Ansonia School District                          2015-16 ELA                            *

                                                                 Level 3&4 Met or Exceeded Count  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                                   *
                                                         Math                                  *
Amistad Academy District                         2015-16 ELA                                   *
                                                         Math                                 10
Ansonia School District                          2015-16 ELA                                   *

                                                                 Level 3&4 Met or Exceeded %  \
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA                               *
                                                         Math                              *
Amistad Academy District                         2015-16 ELA                               *
                                                         Math                           22.7
Ansonia School District                          2015-16 ELA                               *

                                                                 Average Score
District                                         year    Subject
Achievement First Hartford Academy Inc. District 2015-16 ELA               529
                                                         Math              537
Amistad Academy District                         2015-16 ELA               515
                                                         Math              470
Ansonia School District                          2015-16 ELA               476

In [6]:
# combine the two sheets
scores_both = pd.concat([scores_16,scores_17])

In [7]:
# this is how you select one row
scores_both.loc["Achievement First Hartford Academy Inc. District","2015-16","Math"]

District Code                                    ="2880013"
Total Number of Students                                 32
Total Number Tested                                      30
Connecticut School Day SAT Participation Rate          93.8
Total Numberwith Scored Tests                            30
Level 1 Not Met Count                                     *
Level 1 Not Met Count %                                   *
Level 2 Approaching Count                                13
Level 2 Approaching %                                  43.3
Level 3 Met Count                                        14
Level 3 Met Count %                                    46.7
Level 4 Exceeded Count                                    *
Level 4 Exceeded Count %                                  *
Level 3&4 Met or Exceeded Count                           *
Level 3&4 Met or Exceeded %                               *
Average Score                                           537
Name: (Achievement First Hartford Academy Inc. District, 2015-16, Math), dtype: object

In [8]:
# make a list of school districts
districts = []
for index, row in scores_both.iterrows():
    if index[0] not in districts:
        districts.append(index[0])
        
print districts[:10],"..."

['Achievement First Hartford Academy Inc. District', 'Amistad Academy District', 'Ansonia School District', 'Area Cooperative Educational Services', 'Avon School District', 'Berlin School District', 'Bethel School District', 'Bloomfield School District', 'Bolton School District', 'Branford School District'] ...